name: trade-bot

on:
  schedule:
    - cron: '0 9 * * 1-5'
    - cron: '0 12 * * 1-5'
    - cron: '0 15 * * 1-5'
    - cron: '50 15 * * 1-5'

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - run: pip install yfinance requests

      # 通常BOT
      - name: Run Trade Bot
        if: github.event.schedule != '50 15 * * 1-5'
        run: python trade_bot.py
        env:
          LINE_CHANNEL_ACCESS_TOKEN: ${{ secrets.LINE_CHANNEL_ACCESS_TOKEN }}
          LINE_USER_ID: ${{ secrets.LINE_USER_ID }}
          RUN_MODE: trade

      # シナリオ
      - name: Run Pre Scenario
        if: github.event.schedule == '50 15 * * 1-5'
        run: python trade_bot.py
        env:
          LINE_CHANNEL_ACCESS_TOKEN: ${{ secrets.LINE_CHANNEL_ACCESS_TOKEN }}
          LINE_USER_ID: ${{ secrets.LINE_USER_ID }}
          RUN_MODE: prescenario

      # 分析
      - name: Run Analyze Logs
        if: github.event.schedule == '50 15 * * 1-5'
        run: python analyze_logs.py
        env:
          LINE_CHANNEL_ACCESS_TOKEN: ${{ secrets.LINE_CHANNEL_ACCESS_TOKEN }}
          LINE_USER_ID: ${{ secrets.LINE_USER_ID }}
